# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


import pytest

from granite_core.search.scraping.types import ScrapedSearchResult
from granite_core.search.types import SearchResult
from granite_core.search.vector_store import VectorStoreWrapper
from granite_core.search.vector_store.factory import VectorStoreWrapperFactory


@pytest.mark.asyncio
async def test_vector_store() -> None:
    """Test basic vector_store infrastructure"""
    vs: VectorStoreWrapper = VectorStoreWrapperFactory.create()

    scraped_search_result = ScrapedSearchResult(
        search_result=SearchResult(
            title="IBM Wikipedia Article",
            body="International Business Machines Corporation (using the trademark IBM), nicknamed Big Blue, is an American multinational technology company headquartered in Armonk, New York, and present in over 175 countries.",  # noqa: E501
            href="https://en.wikipedia.org/wiki/IBM",
        ),
        url="https://en.wikipedia.org/wiki/IBM",
        title="IBM Wikipedia Article",
        raw_content="""
International Business Machines Corporation (using the trademark IBM), nicknamed Big Blue,[6] is an American multinational technology company headquartered in Armonk, New York, and present in over 175 countries.[7][8] It is a publicly traded company and one of the 30 companies in the Dow Jones Industrial Average.[a][9][10] IBM is the largest industrial research organization in the world, with 19 research facilities across a dozen countries; for 29 consecutive years, from 1993 to 2021, it held the record for most annual U.S. patents generated by a business.
IBM was founded in 1911 as the Computing-Tabulating-Recording Company (CTR), a holding company of manufacturers of record-keeping and measuring systems. It was renamed "International Business Machines" in 1924 and soon became the leading manufacturer of punch-card tabulating systems. During the 1960s and 1970s, the IBM mainframe, exemplified by the System/360 and its successors, was the world's dominant computing platform, with the company producing 80 percent of computers in the U.S. and 70 percent of computers worldwide.[11] Embracing both business and scientific computing, System/360 was the first family of computers designed to cover a complete range of applications from small to large.[12]
IBM debuted in the microcomputer market in 1981 with the IBM Personal Computer; its architecture remains the basis for the majority of personal computers sold today.[13] The company later also found success in the portable space with the ThinkPad. Since the 1990s, IBM has concentrated on computer services, software, supercomputers, and scientific research; it sold its microcomputer division to Lenovo in 2005. IBM continues to develop mainframes, and its supercomputers have consistently ranked among the most powerful in the world in the 21st century.
As one of the world's oldest and largest technology companies, IBM has been responsible for several technological innovations, including the Automated Teller Machine (ATM), Dynamic Random-Access Memory (DRAM), the floppy disk, Generalized Markup Language, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, and the Universal Product Code (UPC) barcode. The company has made inroads in advanced computer chips, quantum computing, artificial intelligence, and data infrastructure.[14][15][16] IBM employees and alumni have won various recognitions for their scientific research and inventions, including six Nobel Prizes and six Turing Awards.[17]
""",  # noqa: E501
    )

    await vs.load([scraped_search_result])

    docs = await vs.asimilarity_search(query="What is IBM nickname?", k=1)
    assert docs and len(docs) == 1
    assert "nicknamed" in docs[0].page_content

    docs = await vs.asimilarity_search(query="When did IBM enter micro computer market?", k=1)
    assert docs and len(docs) == 1
    assert "1981" in docs[0].page_content

    docs = await vs.asimilarity_search(query="When IBM was founded what was the company called?", k=1)
    assert docs and len(docs) == 1
    assert "Computing-Tabulating-Recording Company" in docs[0].page_content
